package com.example.quickshot;
import android.app.*;import android.content.*;import android.media.projection.MediaProjectionManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.Manifest;import android.content.pm.PackageManager;import android.graphics.Color;import android.view.*;import android.widget.*;
public class MainActivity extends Activity{
 private static final int CAPTURE=42,OVERLAY=43;private MediaProjectionManager projection;
 @Override public void onCreate(Bundle b){super.onCreate(b);projection=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);buildUi();}
 private void buildUi(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(36,48,36,24);box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView title=new TextView(this);title.setText("لقطة سريعة");title.setTextSize(28);title.setTextColor(Color.rgb(0,130,145));title.setGravity(Gravity.CENTER);box.addView(title,new LinearLayout.LayoutParams(-1,80));TextView info=new TextView(this);info.setText("فعّل الزر العائم لالتقاط الشاشة فوراً من أي تطبيق.\nستحفظ الصور تلقائياً في مجلد Screenshot.");info.setTextSize(18);info.setTextColor(Color.DKGRAY);info.setGravity(Gravity.CENTER);box.addView(info,new LinearLayout.LayoutParams(-1,0,1));Button start=new Button(this);start.setText("تفعيل الزر العائم");start.setTextSize(18);box.addView(start,new LinearLayout.LayoutParams(-1,64));start.setOnClickListener(v->enable());setContentView(box);}
 private void enable(){if(!Settings.canDrawOverlays(this)){startActivityForResult(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())),OVERLAY);return;}requestProjection();}
 private void requestProjection(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7);startActivityForResult(projection.createScreenCaptureIntent(),CAPTURE);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==OVERLAY){if(Settings.canDrawOverlays(this))requestProjection();}else if(r==CAPTURE&&c==RESULT_OK&&d!=null){Intent s=new Intent(this,ScreenshotService.class);s.putExtra("resultCode",c);s.putExtra("data",d);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);Toast.makeText(this,"تم تفعيل زر الالتقاط",Toast.LENGTH_SHORT).show();finish();}}
}
