package com.example.quickshot;
import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;
public class ScreenshotService extends Service{
 private WindowManager wm;private View bubble,flash;private MediaProjection projection;private ImageReader reader;private VirtualDisplay display;private int w,h,density;private boolean busy;
 @Override public void onCreate(){super.onCreate();createChannel();if(Build.VERSION.SDK_INT>=29)startForeground(10,notification(),ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION);else startForeground(10,notification());wm=(WindowManager)getSystemService(WINDOW_SERVICE);showBubble();}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("capture","لقطة سريعة",NotificationManager.IMPORTANCE_LOW);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
 private Notification notification(){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,"capture"):new Notification.Builder(this);return b.setSmallIcon(android.R.drawable.ic_menu_camera).setContentTitle("لقطة سريعة تعمل").setContentText("اضغط الزر العائم لالتقاط الشاشة").setOngoing(true).build();}
 private int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}private WindowManager.LayoutParams lp(int type){WindowManager.LayoutParams p=new WindowManager.LayoutParams(dp(58),dp(58),type,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);p.gravity=Gravity.END|Gravity.CENTER_VERTICAL;p.y=-dp(70);return p;}
 private void showBubble(){bubble=new ImageButton(this);bubble.setImageResource(R.drawable.ic_camera);bubble.setBackgroundColor(Color.TRANSPARENT);bubble.setPadding(dp(5),dp(5),dp(5),dp(5));bubble.setOnClickListener(v->capture());int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;wm.addView(bubble,lp(type));}
 private void setBubble(boolean on){if(bubble!=null)bubble.setVisibility(on?View.VISIBLE:View.INVISIBLE);}private void capture(){if(busy||projection==null)return;busy=true;setBubble(false);showFlash();new Handler().postDelayed(()->grabFrame(),140);}
 private void showFlash(){flash=new View(this);flash.setBackgroundColor(Color.WHITE);flash.setAlpha(.28f);int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;WindowManager.LayoutParams p=new WindowManager.LayoutParams(-1,-1,type,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE,PixelFormat.TRANSLUCENT);wm.addView(flash,p);flash.animate().alpha(0f).setDuration(220).withEndAction(()->{if(flash!=null){wm.removeView(flash);flash=null;}}).start();}
 private void grabFrame(){try{DisplayMetrics m=getResources().getDisplayMetrics();w=m.widthPixels;h=m.heightPixels;density=m.densityDpi;reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);display=projection.createVirtualDisplay("QuickShot",w,h,density,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,null);new Handler().postDelayed(()->saveFrame(),180);}catch(Exception e){finishCapture();}}
 private void saveFrame(){Image image=null;try{image=reader.acquireLatestImage();if(image==null){finishCapture();return;}Image.Plane p=image.getPlanes()[0];int pw=p.getRowStride()/p.getPixelStride();Bitmap b=Bitmap.createBitmap(pw,h,Bitmap.Config.ARGB_8888);b.copyPixelsFromBuffer(p.getBuffer());Bitmap cropped=Bitmap.createBitmap(b,0,0,Math.min(w,pw),h);String name="Screenshot_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".png";OutputStream out;if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name);v.put(MediaStore.Images.Media.MIME_TYPE,"image/png");v.put(MediaStore.Images.Media.RELATIVE_PATH,Environment.DIRECTORY_PICTURES+"/Screenshot");v.put(MediaStore.Images.Media.IS_PENDING,1);Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);out=getContentResolver().openOutputStream(u);cropped.compress(Bitmap.CompressFormat.PNG,100,out);out.close();v.clear();v.put(MediaStore.Images.Media.IS_PENDING,0);getContentResolver().update(u,v,null,null);}else{File dir=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES),"Screenshot");dir.mkdirs();out=new FileOutputStream(new File(dir,name));cropped.compress(Bitmap.CompressFormat.PNG,100,out);out.close();}b.recycle();cropped.recycle();Toast.makeText(this,"تم حفظ لقطة الشاشة",Toast.LENGTH_SHORT).show();}catch(Exception ignored){}finally{if(image!=null)image.close();finishCapture();}}
 private void finishCapture(){if(display!=null){display.release();display=null;}if(reader!=null){reader.close();reader=null;}setBubble(true);busy=false;}
 @Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&i.hasExtra("data")){MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=m.getMediaProjection(i.getIntExtra("resultCode",0),(Intent)i.getParcelableExtra("data"));}return START_STICKY;}
 @Override public void onDestroy(){if(bubble!=null)wm.removeView(bubble);if(projection!=null)projection.stop();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
